"""init migration

Revision ID: a0d264ad638a
Revises: 
Create Date: 2023-11-14 09:42:58.758992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d264ad638a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('special_attack', sa.Integer(), nullable=True),
    sa.Column('special_defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    op.create_index(op.f('ix_pokemons_pokemon_id'), 'pokemons', ['pokemon_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemons_pokemon_id'), table_name='pokemons')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
